-- Migration 045: Command-rule provenance
-- command_rules steer output handling (truncate / summary) in the PreToolUse
-- hook. They can be authored by a human OR generated by the LLM curator from
-- observed command patterns. Tag who authored each rule so model-derived rules
-- are auditable and can be excluded from enforcement when desired:
--   'manual'  — human-authored (default; trusted)
--   'curator' — generated by the LLM curator (eagle-mem curate)
-- Default 'manual' preserves every existing row and the current behavior. The
-- getter (eagle_get_command_rule) honors `token_guard.trust_learned_rules`
-- (default true); set it false to apply only 'manual' rules.

ALTER TABLE command_rules ADD COLUMN source TEXT NOT NULL DEFAULT 'manual';

CREATE INDEX IF NOT EXISTS idx_command_rules_source ON command_rules(source);
