#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# Eagle Mem — Help
# ═══════════════════════════════════════════════════════════

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKAGE_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"

. "$SCRIPTS_DIR/style.sh"

version=$(node -e "console.log(require('$PACKAGE_DIR/package.json').version)" 2>/dev/null || echo "unknown")

eagle_banner

echo -e "  ${BOLD}Eagle Mem${RESET} ${DIM}v${version}${RESET}"
echo -e "  ${DIM}Lightweight persistent memory for Claude Code${RESET}"
echo ""
echo -e "  ${BOLD}Usage:${RESET}"
echo -e "    eagle-mem ${CYAN}<command>${RESET}"
echo ""
echo -e "  ${BOLD}Commands:${RESET}"
echo -e "    ${CYAN}search${RESET}      Search past sessions, files, and observations"
echo -e "    ${CYAN}tasks${RESET}       Manage tracked tasks (add, done, block, list)"
echo -e "    ${CYAN}overview${RESET}    View or set project overview"
echo -e "    ${CYAN}memories${RESET}    Browse and search Claude Code memories, plans, and tasks"
echo -e "    ${CYAN}scan${RESET}        Analyze a project and generate an overview"
echo -e "    ${CYAN}index${RESET}       Index source files for code-level search"
echo -e "    ${CYAN}prune${RESET}       Remove old observations and orphaned chunks"
echo -e "    ${CYAN}install${RESET}     Set up hooks, database, and skills"
echo -e "    ${CYAN}uninstall${RESET}   Remove hooks and optionally delete data"
echo -e "    ${CYAN}update${RESET}      Re-deploy hooks and run new migrations"
echo -e "    ${CYAN}help${RESET}        Show this help message"
echo -e "    ${CYAN}version${RESET}     Show version number"
echo ""
echo -e "  ${BOLD}Examples:${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search \"auth bug\"  ${DIM}# Search memory${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --timeline  ${DIM}# Recent sessions${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem tasks              ${DIM}# List tasks${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem tasks add \"Fix X\"  ${DIM}# Add a task${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem overview           ${DIM}# View overview${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem scan .             ${DIM}# Scan current project${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem index .            ${DIM}# Index source files${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem memories           ${DIM}# List mirrored memories${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem memories sync      ${DIM}# Backfill memories + plans + tasks${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem memories plans     ${DIM}# List captured plans${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem memories tasks     ${DIM}# List captured tasks${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem prune              ${DIM}# Clean old data${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem install            ${DIM}# First-time setup${RESET}"
echo ""
echo -e "  ${BOLD}What it does:${RESET}"
echo -e "    ${DOT} Saves session summaries to a shared SQLite database"
echo -e "    ${DOT} Injects relevant memory at session start"
echo -e "    ${DOT} Searches past sessions when you ask related questions"
echo -e "    ${DOT} Tracks file operations across sessions"
echo -e "    ${DOT} Mirrors Claude Code memories, plans, and tasks into FTS5-searchable storage"
echo -e "    ${DOT} Provides task management for complex multi-step work"
echo ""
echo -e "  ${BOLD}Skills${RESET} ${DIM}(available inside Claude Code):${RESET}"
echo -e "    ${CYAN}/eagle-mem-search${RESET}    Search past sessions and observations"
echo -e "    ${CYAN}/eagle-mem-tasks${RESET}     Break work into tracked subtasks"
echo -e "    ${CYAN}/eagle-mem-overview${RESET}  Generate a persistent project summary"
echo ""
echo -e "  ${DIM}Skills use these CLI commands under the hood — no raw SQL.${RESET}"
echo ""
echo -e "  ${DIM}https://github.com/eagleisbatman/eagle-mem${RESET}"
echo ""
