#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════
# Eagle Mem — Help
# ═══════════════════════════════════════════════════════════

SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
PACKAGE_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"

. "$SCRIPTS_DIR/style.sh"

version=$(jq -r .version "$PACKAGE_DIR/package.json" 2>/dev/null || echo "unknown")

eagle_banner

echo -e "  ${BOLD}Eagle Mem${RESET} ${DIM}v${version}${RESET}"
echo -e "  ${DIM}Shared memory, release guardrails, RTK token protection, and worker lanes${RESET}"
echo -e "  ${DIM}for Claude Code and Codex.${RESET}"
echo ""
echo -e "  ${BOLD}Core commands:${RESET}"
echo -e "    ${CYAN}install${RESET}     First-time setup: hooks, database, skills"
echo -e "    ${CYAN}update${RESET}      Re-deploy hooks and run migrations"
echo -e "    ${CYAN}uninstall${RESET}   Remove hooks and optionally delete data"
echo -e "    ${CYAN}search${RESET}      Search past sessions, memories, and code"
echo -e "    ${CYAN}health${RESET}      Diagnose pipeline health and background automation"
echo -e "    ${CYAN}updates${RESET}     Auto-update status and policy"
echo -e "    ${CYAN}overview${RESET}    Build or view project overview"
echo -e "    ${CYAN}session${RESET}     Save a manual session summary"
echo -e "    ${CYAN}memories${RESET}    View/sync agent memories"
echo -e "    ${CYAN}tasks${RESET}       View mirrored tasks"
echo ""
echo -e "  ${BOLD}Safety and token controls:${RESET}"
echo -e "    ${CYAN}feature${RESET}     Track, verify, and unblock feature changes"
echo -e "    ${CYAN}guard${RESET}       Manage regression guardrails for files"
echo -e "    ${CYAN}config${RESET}      View/change providers, RTK, and token guard settings"
echo -e "    ${CYAN}statusline${RESET}  Print compact Eagle Mem statusline"
echo ""
echo -e "  ${BOLD}Automation and coordination:${RESET}"
echo -e "    ${CYAN}curate${RESET}      Run curator (co-edits, hot files, guardrails)"
echo -e "    ${CYAN}orchestrate${RESET} Durable worker-lane coordination"
echo -e "    ${CYAN}prune${RESET}       Clean old sessions and stale data"
echo ""
echo -e "  ${BOLD}What it protects:${RESET}"
echo -e "    ${DIM}Recall${RESET}       Project overview, summaries, memories, plans, tasks, code index"
echo -e "    ${DIM}Guardrails${RESET}   Decisions, gotchas, feature verification, stale memory warnings"
echo -e "    ${DIM}Tokens${RESET}       Compact hook recall and optional RTK shell-output routing"
echo -e "    ${DIM}Lanes${RESET}        Cross-agent worker status, worktrees, logs, validation, handoffs"
echo -e "    ${DIM}Updates${RESET}      Patch fixes install automatically by default"
echo ""
echo -e "  ${BOLD}Search modes:${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search \"auth bug\"    ${DIM}# keyword search${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --timeline     ${DIM}# recent sessions${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --overview     ${DIM}# project overview${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --memories     ${DIM}# mirrored memories${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --tasks        ${DIM}# in-flight tasks${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --files        ${DIM}# hot files${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem search --stats        ${DIM}# project stats${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem session save --summary \"fixed auth\""
echo ""
echo -e "  ${BOLD}Anti-regression:${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem feature pending       ${DIM}# pending release blockers${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem feature verify NAME   ${DIM}# verify current diff after testing${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem feature waive ID      ${DIM}# intentional exception${RESET}"
echo ""
echo -e "  ${BOLD}Orchestration:${RESET}"
echo -e "    ${DIM}Agent-run protocol for broad multi-lane work; users normally do not run this manually.${RESET}"
echo -e "    ${DIM}Codex sessions spawn Claude workers; Claude sessions spawn Codex workers by default.${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem orchestrate init \"Ship release\""
echo -e "    ${DIM}\$${RESET} eagle-mem orchestrate lane add api --agent codex --validate \"npm test\""
echo -e "    ${DIM}\$${RESET} eagle-mem orchestrate spawn api       ${DIM}# worktree + worker process${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem orchestrate sync            ${DIM}# reconcile worker status${RESET}"
echo -e "    ${DIM}\$${RESET} eagle-mem orchestrate handoff --write docs/handoff-context.md"
echo ""
echo -e "  ${BOLD}Skills${RESET} ${DIM}(inside Claude Code and Codex sessions):${RESET}"
echo -e "    ${CYAN}eagle-mem-search${RESET}       Search memory and past sessions"
echo -e "    ${CYAN}eagle-mem-overview${RESET}     Build or update project overview"
echo -e "    ${CYAN}eagle-mem-memories${RESET}     View/sync agent memories"
echo -e "    ${CYAN}eagle-mem-tasks${RESET}        TaskAware Compact Loop for multi-step work"
echo -e "    ${CYAN}eagle-mem-orchestrate${RESET}  Orchestrator/worker lane handoffs"
echo ""
echo -e "  ${DIM}Everything else is automatic — scan, index, prune, and${RESET}"
echo -e "  ${DIM}curator all run in the background via hooks.${RESET}"
echo ""
echo -e "  ${DIM}https://github.com/eagleisbatman/eagle-mem${RESET}"
echo ""
